const ACTION_TYPE = {
	SET_TODOS: 'SET_TODOS',
	ADD_TODO: 'ADD_TODO',
	SORTED_TODO: 'SORTED_TODO',
	REMOVE_TODO: 'REMOVE_TODO',
	SET_TODO_CHECKED: 'SET_TODO_CHECKED',
	SET_EDIT: 'SET_EDIT',
	SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
	SET_TITLE: 'SET_TITLE',
	SET_TODO_VALUE: 'SET_TODO_VALUE',
};
export default ACTION_TYPE;
